fix: OFF-241 typo in Error class breaks the action
CI workflows were failing with the following message: 
```
/home/runner/work/_actions/ohpensource/ensure-conventional-commits-gh-action/v1.1.0/modules/settings-provider.js:10
        throw new error('file provided does not exists')
              ^
TypeError: error is not a constructor
```
This should fix the problem